# Generated by Django 5.0.3 on 2024-03-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Cleaning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="markeddate",
            name="User_Name",
            field=models.CharField(default="Unkown User", max_length=30),
        ),
    ]
