# Generated by Django 5.0.2 on 2024-03-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Guestroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room", models.CharField(max_length=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("book", "Book"), ("unavailable", "Item is Booked")],
                        max_length=100,
                    ),
                ),
                ("checkin_date", models.DateField()),
                ("checkout_date", models.DateField()),
                ("price", models.CharField(max_length=100)),
                ("manager_validation", models.CharField(default="NO", max_length=10)),
                ("date", models.DateField()),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
            ],
        ),
    ]
