# Generated by Django 5.0.2 on 2024-03-16 09:41

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Hall Manager", "Hall Manager"),
                        ],
                        max_length=15,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", authentication.models.UserManager()),
            ],
        ),
    ]
